artifact_location: /Users/salahmneimne/Desktop/MBD2025/TERM 2/MLOPS /IE-MLOPS-NYC-TAXIS/04-deployment/127.0.0.1:5000/0
creation_time: 1772626683249
experiment_id: '0'
last_update_time: 1772626683249
lifecycle_stage: active
name: Default
workspace: default
